version: '3.8'

services:
    # PHP-FPM Application
    app:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        container_name: ai-generator-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ../:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - generator-network
        depends_on:
            - redis

    # Nginx Web Server
    nginx:
        image: nginx:alpine
        container_name: ai-generator-nginx
        restart: unless-stopped
        ports:
            - "8089:80"
        volumes:
            - ../:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - generator-network
        depends_on:
            - app

    # Redis Cache & Sessions
    redis:
        image: redis:7-alpine
        container_name: ai-generator-redis
        restart: unless-stopped
        ports:
            - "6380:6379"
        volumes:
            - redis-data:/data
        networks:
            - generator-network
        command: redis-server --appendonly yes

    # MinIO S3-compatible Storage
    minio:
        image: minio/minio:latest
        container_name: ai-generator-minio
        restart: unless-stopped
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        volumes:
            - minio-data:/data
        networks:
            - generator-network
        command: server /data --console-address ":9001"

networks:
    generator-network:
        driver: bridge

volumes:
    redis-data:
        driver: local
    minio-data:
        driver: local
